dist: xenial

language: java

jdk:
  - openjdk8

script: ./mvnw clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: Test
      script: ./mvnw clean test

addons:
  hosts:
    - rabbit
  apt:
    packages:
      - rabbitmq-server

services:
  - rabbitmq