language: java
jdk:
  - openjdk8

script: ./mvnw clean jacoco:prepare-agent install jacoco:report

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: Test
      script: ./mvnw clean test