language: java
jdk:
  - openjdk8

script: ./mvnw clean install
        ./mvnw clean package -PoutputDir

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: Test
      script: ./mvnw clean test