version: "3.8"
services:
  sputnikfy:
    image: sputnikfy:latest
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
