---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:3.8-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-cluster
spec:
  ports:
    - port: 5672
      targetPort: 5672
      name: app
    - port: 15672
      targetPort: 15672
      name: ui
  selector:
    app: rabbit
  type: NodePort
