---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sputnikfy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sputnikfy
  template:
    metadata:
      labels:
        app: sputnikfy
    spec:
      containers:
      - name: sputnikfy
        image: sputnikfy:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: sputnikfy
spec:
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 8080
  selector:
    app: sputnikfy
  type: NodePort
